name: Atualizar JSON

on:
  workflow_dispatch:
  push:
    paths:
      - electric_cars_portugal.xlsx

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install xlsx

      - name: Atualizar JSON
        run: node scripts/gerar-json.js

      - name: Commit e push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/evmag-carros.json
          git commit -m "Atualização automática do JSON"
          git push
